### PR TITLE
Update fsync.yml

### PR DESCRIPTION
**Pull request by jaspermayone**

### CODE REVIEW

**Comment by reesericci** [comment]
wait why are we syncing so many goddamn files

**Comment by jaspermayone** [comment]
so we don't have to put them all in manually

**Comment by reesericci** [comment]
but we don't need all of these .github files in every repo

**Comment by jaspermayone** [comment]
true. want to fix that in all the places it now needs to be fixed lol?

**Comment by reesericci** [comment]
no

**Review by taciturnaxolotl — APPROVED** [review]

**Pull request merged**
